# Generated by Django 5.1.7 on 2025-04-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crop_detection", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageupload",
            name="confidence",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
