# Generated by Django 5.1.7 on 2025-04-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crop_detection", "0002_imageupload_confidence"),
    ]

    operations = [
        migrations.AddField(
            model_name="forumcomment",
            name="dislikes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="forumcomment",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
