# Generated by Django 5.1.7 on 2025-04-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crop_detection", "0003_forumcomment_dislikes_forumcomment_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageupload",
            name="ai_insights",
            field=models.TextField(blank=True, null=True),
        ),
    ]
